name: Build and Deploy LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: main-pdf
          path: main.pdf
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: main-pdf
          path: .
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .
      - uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GH_PAT }}
          artifact_name: main.pdf
