name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GH_PAT }}

      - name: Commit and push PDF to gh-pages
        run: |
          git config --global user.name "lorenzoFabbri"
          git config --global user.email "lorenzoFabbri@users.noreply.github.com"
          git add main.pdf
          git commit -m "Update PDF"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
