name: Build and Deploy LaTeX document
permissions: write-all

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: true
          fetch-depth: 0
      - uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
      - uses: docker://ghcr.io/michal-h21/make4ht-action:latest
        env:
          command: "make4ht -d out main.tex"
      - run: |
          cd out
          sudo mv main.html index.html
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: main-pdf
          path: main.pdf
      - uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: Current
          files: main.pdf
      - uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.119.0'
      - run: hugo --minify
      - uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.ref == 'refs/heads/gh-pages'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
