name: Build and Deploy LaTeX document

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you use

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure the job has write permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: List directory contents (before upload)
        run: ls -R

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-pdf
          path: main.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy  # Ensure this job runs after the build_and_deploy job
    permissions:
      pages: write  # Ensure the job has write permissions for pages
      id-token: write  # Enable OIDC token permissions

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GH_PAT }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: main-pdf
          path: .

      - name: List directory contents (after download)
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GH_PAT }}
          branch: gh-pages  # Deploy to gh-pages branch
          folder: .  # Deploy from the root directory
