name: Build and Deploy LaTeX document
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: List directory contents (before upload)
        run: ls -R
        shell: bash

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-pdf
          path: main.pdf

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GH_PAT }}

      - name: Download PDF artifact
        uses: actions/download-artifact@v3
        with:
          name: main-pdf
          path: .

      - name: List directory contents (after download)
        run: ls -R
        shell: bash

      - name: Commit and push PDF to gh-pages
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git add main.pdf
          git commit -m "Update PDF"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./  # Directory where main.pdf is located
