name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload PDF file to Pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git config --global user.name "lorenzoFabbri"
          git config --global user.email "lorenzoFabbri@users.noreply.github.com"
          git add main.pdf
          git commit -m "Uploading PDF to Pages."
          git push origin gh-pages
