name: Build LaTeX document
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: List directory contents (before checkout)
        run: ls -R
        shell: bash

      - name: Move PDF to temporary location
        run: mv main.pdf /tmp/main.pdf
        shell: bash

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GH_PAT }}

      - name: Move PDF back from temporary location
        run: mv /tmp/main.pdf ./main.pdf
        shell: bash

      - name: List directory contents (after checkout)
        run: ls -R
        shell: bash

      - name: Commit and push PDF to gh-pages
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your.email@example.com"
          git add main.pdf
          git commit -m "Update PDF"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
