name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Move to gh-pages branch
        run: |
          git config --global user.name "lorenzoFabbri"
          git config --global user.email "lorenzoFabbri@users.noreply.github.com"
          git fetch origin
          git checkout -B gh-pages origin/gh-pages

      - name: Commit and push PDF to gh-pages
        run: |
          git add main.pdf
          git commit -m "Update PDF"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
