name: Build and Deploy LaTeX document
permissions: write-all

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
      - uses: docker://ghcr.io/michal-h21/make4ht-action:latest
        env:
          command: "make4ht -d out main.tex"
      - run: |
          cd out
          sudo mv main.html index.html
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: main-pdf
          path: main.pdf
      - uses: softprops/action-gh-release@v2.0.6
        with:
          tag_name: Current
          files: main.pdf
      - uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./out
